### ISSUE TITLE
Getting Error "TypeError [ERR_INVALID_URL]: Invalid URL"

### ISSUE THREAD

**Issue by Schlauer-Hax** [r7kamura/google-docs-to-markdown#1]
I am currently getting an error when using your action.

I suspect the error to come from https://github.com/r7kamura/google-docs-to-markdown/blob/715a31c0b0c20b361cd443e1a492ca8b6785fa69/index.js#L90 

![image](https://github.com/r7kamura/google-docs-to-markdown/assets/32987311/a3ab2f61-40f1-4ae0-8a03-f78ef4884043)

Is there any way to fix this?

**Comment by r7kamura** [comment]
Perhaps link URLs in the HTML exported from Google Docs has changed recently?  We will have to look again to inspect what HTML is exported when a link is embedded.

**Comment by Schlauer-Hax** [comment]
That could be! That's probably also why this issue also occurs in your google-docs-to-local action. Is there anything I can help with to solve this issue?

**Comment by r7kamura** [comment]
I ran this action now and it worked fine as before. It appears that the behavior has not changed.

- https://github.com/r7kamura/godolog-example
- https://github.com/r7kamura/godolog-example/actions/runs/5113378406

Maybe it fails if it contains a link to a specific pattern of URL 🤔 
Can you export the failing google document as HTML on Google Docs and tell me what it contains?

**Comment by Schlauer-Hax** [comment]
i ran the specific code on the document, getting the same error

![image](https://github.com/r7kamura/google-docs-to-markdown/assets/32987311/76e11b2b-0908-4f3f-9c6e-348a3ec6dbdd)

looks like the problems appears when there is a comment attached to the text

![image](https://github.com/r7kamura/google-docs-to-markdown/assets/32987311/e216ec1b-4b4e-4347-974a-45d0d1a90c67)

**Comment by r7kamura** [comment]
@Schlauer-Hax I fixed this at #2 and released a new version. Can you try it?

**Comment by Schlauer-Hax** [comment]
![image](https://github.com/r7kamura/google-docs-to-markdown/assets/32987311/bb1100ab-7321-4a1a-aa78-c9d6cc5f6d01)

looks like it still fails even after specifying the exact version

**Comment by Schlauer-Hax** [comment]
Maybe a possible workaround would be to check if href starts with https://www.google.com/url?q=. It doesn't even make sense why the try catch would not work

**Comment by r7kamura** [comment]
Ah, sorry I forgot to build dist/index.js! 
I'll publish a new version 😇

**Comment by Schlauer-Hax** [comment]
Ah that makes sense! Thanks for your quick response and help!
